### ISSUE TITLE
true / false / nc do not return expected values.

### ISSUE THREAD

**Issue by ccs4ever** [enkiv2/mycroft#1]
The predicates true/0, false/0, and nc/0 all return NC when run in a query, e.g.

?- true.
=> NC
?- false.
=> NC
?- nc.
=> NC

When incorporated into a predicate such as:

det bar(A) :- true.

?- bar(quux).

The result is NO in all cases.

**Comment by enkiv2** [comment]
true/0 cannot be called as 'true.': it's a predicate, so you must call it using parens: ?-true().

However, true/0 is just sugar for "YES", which is equivalent to <1,1>.

Because 'true' is not an identifier but an atom (no capital letter beginning it), and because it is not called with parens, it will always evaluate to NC when treated as a truth value (but will be considered a string in cases where that is allowed, such as ?- print(true) ).

**Comment by ccs4ever** [comment]
Ah. I see. My mistake :P
